### ISSUE TITLE
Works without setting faunadb key?

### ISSUE THREAD

**Issue by ghost** [netlify/netlify-faunadb-example#14]
This seems like one of those obvious bits of information that's just not coming to me. I used the 1-click deploy button to deploy to netlify, but actually didn't need to follow any of the steps in the readme to get the app working.

I don't have a faunadb account, there's not environment variable file, and no environment variables in the Netlify UI.

Is it suppsoed to work just right out of the box? And also, how is that happening? because that's very cool.

**Comment by armandoborge** [comment]
AFAIK There is a FaunaDB addon under the hood that creates the DB, connect it to your site and injects the ENV variables.

**Comment by DavidWells** [comment]
Yep the one click flow automatically provisions the fauna dB under the hood.
