### ISSUE TITLE
Environment variables are potentially vulnerable to a malicious deploy preview

### ISSUE THREAD

**Issue by calebmisclevitz** [netlify/netlify-faunadb-example#4]
I stumbled upon this tutorial while attempting to design a similar app. I'm concerned about the potential security implications of including Netlify Functions in an open source project.

If deploy previews are enabled for PRs, can a contributor submit a malicious PR to expose `process.env`?

We seem to have come across this in our similar project:

<img width="1006" alt="screen shot 2019-01-09 at 12 05 14 pm" src="https://user-images.githubusercontent.com/5323407/50925915-8d094680-1408-11e9-84a7-95069e8918dc.png">

I'm excited about using Netlify Functions to proxy API requests, and I'm curious about any thoughts and recommendations on this. Does Netlify recommend disabling deploy previews or otherwise configuring them in an open source project that utilizes Netlify Functions?

**Comment by sw-yx** [comment]
thanks for your concern!

env vars can have contexts - https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

so just be sure that your prod stuff is in a prod context and your deploy preview stuff is in a different one.

pretty neat huh!

**Comment by egardner** [comment]
Thanks, @sw-yx – we figured Netlify had set up some way to avoid this problem, just weren't sure what it was.

It sounds like a good practice for a public project that talks to an API would be to do the following:
- Create a dummy account for whatever service is being used (Airtable in this case)
- Put the access key for that account into `netlify.toml` in `[context.deploy-preview.environment]`. This will be exposed in the repo for all to see, but it's only dummy data
- Keep the production access key in the Netlify admin; users who deploy their own copy of the app to their own Netlify instance will have to provide their own production data (their own Airtable account or whatever).

Is there anything I'm overlooking here? Thanks again!

**Comment by sw-yx** [comment]
yup, thats about it!

i'll be honest that i havent precisely done this myself because i havent needed to but this is exactly how it would work in theory. if you try it and run into any problems (including security concerns), please report here and i'll do my best to help you research/resolve.

i'll also blogpost about this to raise awareness.
